# Generated by Django 4.0.6 on 2022-12-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nome')),
                ('project', models.CharField(choices=[('analyser', 'Medidor de Energia')], default='analyser', max_length=15)),
                ('ip_addr', models.GenericIPAddressField(verbose_name='Endereço IP')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
    ]
